apiVersion: v1
kind: Pod
metadata:
  name: httpecho
  labels:
    app: httpecho
spec:
  containers:
  - name: httpecho
    image: mendhak/http-https-echo:latest
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: httpecho
spec:
  selector:
    app: httpecho
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpecho
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  rules:
  #- host: httpecho.duckdns.org          // Replace with your dns.
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpecho
            port:
              number: 8080 
  # Im using self-signed certificates since I'm on my homelab cluster, more info: https://medium.com/@vedant13111998/ingress-setup-with-self-signed-certificate-for-testing-in-kubernetes-a2969f518326
  tls:
    - hosts:
      #  - httpecho.duckdns.org // Replace with your CN 
      secretName: httpecho-tls